# This workflow will install Python dependencies, run full checks defined in `.pre-commit-config.yaml` with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push]

jobs:
  application:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[app]
    - name: Check import errors of the application
      run: |
        python app.py
    - name: Reinstall depedencies from `requirements.txt`
      run: |
        pip freeze | xargs pip uninstall -y
        pip install -r requirements.txt
    - name: Check import errors of the application again for `requirements.txt`
      run: |
        python app.py
